required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/kube-openapi/cmd/openapi-gen"
]

[[constraint]]
  name = "github.com/gardener/gardener"
  version = "^0.19.0"

[[override]]
  name = "github.com/gardener/machine-controller-manager"
  version = "0.12.0"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "0.1.9"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.1"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.1"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "github.com/argoproj/argo"
  branch = "master"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "gopkg.in/fsnotify/fsnotify.v1"


# Dependencies for testing purposes only
[[constraint]]
  name = "github.com/onsi/gomega"
  version = "~1.3.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "~1.4.0"

[prune]
  unused-packages = true
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false

  [[prune.project]]
    name = "k8s.io/kube-openapi"
    unused-packages = false
    non-go = false
