images:
- name: argo-ui
  sourceRepository: github.com/argoproj/argo
  repository: argoproj/argocli
  tag: "v2.9.5"
- name: argo-workflow-controller
  sourceRepository: github.com/argoproj/argo
  repository: argoproj/workflow-controller
  tag: "v2.9.5"
- name: argo-executor
  sourceRepository: github.com/argoproj/argo
  repository: argoproj/argoexec
  tag: "v2.9.5"
- name: reserve-excess-capacity
  sourceRepository: github.com/argoproj/argo
  repository: gcr.io/google_containers/pause-amd64
  tag: "3.1"
- name: minio
  sourceRepository: github.com/minio/minio
  repository: minio/minio
  tag: "RELEASE.2020-04-04T05-39-31Z"
- name: loki
  sourceRepository: https://github.com/grafana/loki
  repository: grafana/loki
  tag: "2.0.0"
- name: promtail
  sourceRepository: https://github.com/grafana/loki/tree/master/docs/clients/promtail
  repository: grafana/promtail
  tag: "2.0.0"
